### ISSUE TITLE
Shows readme on front page

### ISSUE THREAD

**Issue by konsumer** [sqldef/sqldef.github.io#1]
it switched to showing the README instead of the demo.

I think it's the "pages" setting that was pointed to /docs sub-folder, but now is the root in master.

I will set it back for now.

**Comment by k0kubun** [comment]
It's trivial, but using `/docs` might be helpful to avoid distributing files like sqldef-wasm.go or Makefile (or README.md). But I guess you didn't like working on /docs sub-folder so much?

**Comment by konsumer** [comment]
That only works for non-org pages. I was originally doing that, but it stopped working when repo moved to sqldef.github.io. for org pages master root (not docs/ or gh-pages branch) is the webroot.

**Comment by k0kubun** [comment]
Oh, interesting. It seemed to work at first and so I left that after the rename, but then your changes make sense. Thank you.
